// generated by google ai studio

import { ProviderType } from './ai';

// 1. Defina exatamente quais chaves existem e o tipo do valor de cada uma
export interface CustomLocalStorageMap {
  'byok_provider': ProviderType;          // ex: 'openai' | 'anthropic' | 'custom'
  'byok_api_key': string;
  'byok_base_url': string;
  'byok_selected_model': string;
}

// 2. Sobrescreve a interface nativa do navegador (Storage) usando Generics
declare global {
  interface Storage {
    getItem<K extends keyof CustomLocalStorageMap>(key: K): CustomLocalStorageMap[K] | null;
    
    setItem<K extends keyof CustomLocalStorageMap>(key: K, value: CustomLocalStorageMap[K]): void;
    
    removeItem<K extends keyof CustomLocalStorageMap>(key: K): void;
  }
}